names=("JACKFRUIT", "CUSTARDAPPLE", "LYCHEE", "PINEAPPLE", "BER", "PEACH",
                   "ALPHONSOMANGO", "KOKUM", "STARFRUIT", "BLACKJAMUN", "MULBERRY", "PLUM",
                   "FIG", "INDIANGOOSEBERRY", "BAEL", "ROSEAPPLE", "STRAWBERRY", "DRAGONFRUIT",
                   "AVOCADO", "TAMARIND")