# Creating a set of Telugu hero names in uppercase
names= (
    "CHIRANJEEVI", "NAGARJUNA", "BALAKRISHNA", "VENKATESH", "PRABHAS", "MAHESHBABU",
    "ALLUARJUN", "RAMCHARAN", "NTRJR", "PAWANKALYAN", "SAIDHARAMTEJ", "VARUNTEJ",
    "VIJAYDEVERAKONDA", "SHARWANAND", "NITHIIN", "ADIVISESH", "RAVITEJA", "NAGACHAITANYA",
    "SUDHEERBABU", "SANDEEPKISHAN", "GOPICHAND", "RAMPOTHINENI"
)

